---
title: "Fisheries Atlas Indicators"
resource_files:
- Rscripts/helper_functions_FishAtlas.R
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
  # orientation: rows
---

```{r global, include=FALSE}

options(shiny.sanitize.errors = FALSE)

# dirMain <-getwd()
dirMain <-'/home/ae/Documents/PERSONAL/FAO/BlueCloud/Indicators/Fisheries_Atlas_Indicators_Shiny'
dirRScripts <- paste(dirMain,"/Rscripts/",sep='')

# parameter and run/seed info
# dirWS <- "https://goo.gl/mo1Tz7"
# dirWS<-"https://docs.google.com/spreadsheets/d/1CRGaJlOaCMDRqnIOU9TxFHi7OkcM7iF1wvVeZlH_A04/edit?usp=sharing"
dirWS    <- paste(dirMain, "/data/", sep="")
dirData    <- paste(dirMain, "/data/", sep="")
# dirData <- "http://mdst-macroes.ird.fr:8080/thredds/dodsC/BlueBridge/IOTC/"
#######################################################

########### SOURCE LIBRARIES AND FUNCTIONS ############
library(pacman)
p_load('shiny','plyr','reshape2','ggplot2','ncdf4','flexdashboard','plotly','devtools','Rcpp','shinyWidgets','RColorBrewer')
# install_github('ramnathv/rCharts', force= TRUE)
# library(shiny)
require(rCharts)
# library(plyr)
# library(reshape2)
# library(ggplot2)
# library(ncdf4)
# library(flexdashboard)
# library(plotly)
library(tidyverse)


# run_parameters <- read.csv(dirWS)
# run_parameters <- read.csv(paste(dirWS, "run_spec_ss3.csv", sep=""))
run_parameters <- read.csv(paste(dirWS, "fisheries_atlas_assessments.csv", sep=""))

r_seed <- 1
#######################################################

```


```{r, include=FALSE}
source(paste(dirRScripts,'helper_functions_FishAtlas.R',sep=''))
## extract CPUE data from .nc files - Obs_cpue, Exp_cpue, Dev_cpue, and calculate standardised deviations
CPUE_plot <- reactive({read_CPUE_data(paste(input$Model),input$Run, dir_save=paste(dirData,sep=''))})
## extract Lenbase data from .nc files - Obs_len, Exp_len
LEN_plot <- reactive({read_LEN_data(paste(input$Model),input$Run, dir_save=paste(dirData,sep=''))})
## extract Recruitment Deviation data from .nc files - RecDev_val, RecDev_lci, RecDev_uci
RecDev_plot <- reactive({read_RecDev_data(paste(input$Model),input$Run,dir_save=paste(dirData,sep=''))})
## extract Recruitment_0 data from .nc files - re0
R0_plot <- reactive({read_R0_data(paste(input$Model),input$Run,dir_save=paste(dirData,sep=''))})
## extract SSB data from .nc files - re0
SSB_plot <- reactive({read_SSB_data(paste(input$Model),input$Run,dir_save=paste(dirData,sep=''))})
## extract Total biomass data from .nc files - Biomass_all_ts
Bio_plot <- reactive({read_Bio_data(paste(input$Model),input$Run,dir_save=paste(dirData,sep=''))})
## extract F/Fmsy data from .nc files - FFmsy
FFMSY_plot <- reactive({read_ffmsy_data(paste(input$Model),input$Run,dir_save=paste(dirData,sep=''))})
## extract size selectivity data from .nc files - sizeselex
Ssel_plot <- reactive({read_Ssel_data(paste(input$Model),input$Run,dir_save=paste(dirData,sep=''))})
## extract age selectivity data from .nc files - ageselex
Asel_plot <- reactive({read_Asel_data(paste(input$Model),input$Run,dir_save=paste(dirData,sep=''))})
## catchbyOcean
CatchByOcean_plot<-reactive({read_CatchByOcean_data(input$Ocean, input$Region,dir_save=paste(dirData,sep=''))})
```

Home
=====================================
** Welcome to the Fisheries Atlas **


Stock statistics
=====================================
Select input {.sidebar}
-------------------------------------------------

```{r}
# library(data.table)
# run_stats<-data.table(run_stats)
run_stats <- tibble(read.csv(paste(dirWS, "fish_stats.csv", sep=""),sep=',',stringsAsFactors = FALSE))
selectInput(inputId='Ocean',
            label='Ocean(s)',
            choices=unique(run_stats$OCEAN),
            selected=unique(run_stats$OCEAN)[1]
)


  #### Dynamic user inputs
  # The following reactive function returns orders from a selected class
 region_subset <- reactive({ sort(unique(run_stats$REGION[which(run_stats$OCEAN==input$Ocean)])) })
  output$regionSelex <- renderUI({
    selectInput(inputId="Region", label="Region(s)", choices=region_subset(), multiple=FALSE, selected=region_subset()[1])
  })
  uiOutput("regionSelex")

 # species_subset <- reactive({ sort(unique(run_stats$SPECIES[which(run_stats$OCEAN==input$Ocean & run_stats$REGION==input$Region )])) })
 # output$speciesSelex <- renderUI({
 #   selectInput(inputId="Species", label="Species", choices=species_subset(), multiple=FALSE, selected=species_subset()[1])
 # })
 # uiOutput("speciesSelex")

```


Row {.tabset .tabset-fade}
-------------------------------------

### Catch by ocean
<!-- - can include annual catch by ocean, FAO major fishing area, region: Choose All as default, can (de)select individual areas. By species, species group -->
<!-- uses tuna atlas graph, with fishstatj, sdg14.4.1 as dataset -->

<!-- Can include a filter for annual or monthly data -->

<!-- Can combine catch by region with the gridded data into one page/tabe -->
```{r}
renderPlot({
  CatchbyOcean2plot <- CatchByOcean_plot()
  #setup the palette
  my.colors <- brewer.pal(length(unique(CatchbyOcean2plot$Model_run)), "Set1")
  names(my.colors) <- unique(CatchbyOcean2plot$Model_run)
  
  # species.label <- CatchbyOcean2plot$SPECIES
  # species.URI <- CatchbyOcean2plot$SPECIES
  #################### CATCH BY OCEAN ####################
   resultPlot <- ggplot(CatchbyOcean2plot, aes(x=YEAR, y=QUANTITY, group=REGION)) + 
      geom_area(aes(fill=OCEAN), position="stack") + 
      geom_line(position="stack", color="grey20") + 
      scale_fill_manual(name="Ocean", values=my.colors) +
      xlab("Year") + ylab("Catches in thousand tons") + 
      # ggtitle(paste(species.label, "catches by Ocean")) +
      theme(legend.position="bottom")
  # ggplotly(resultPlot)
  resultPlot
  
  # ############# CPUE FIT: OBSERVED V PREDICTED ###########
  # p <- ggplot(na.exclude(CatchbyOcean2plot), aes(x=Year, y=Obs))
  # p <- p+geom_point(size=0.7,col='black')+geom_line(col='black')+geom_line(aes(y=Exp, colour=Model_run))+
  #   facet_wrap(~Fleet,ncol=2)#+scales='free_y'+ggtitle("CPUE fit: Observed v Predicted")#as.numeric(as.character(input$Run)))
  # ggplotly(p)
  ########################################################
})

```


### Catch by gear
<!-- RMFO/RFB data, by ocean, by region, by RFMO/RFB, by species group, by species -->

<!-- Can include a filter for annual or monthly data -->


<!-- # -->
<!-- # ### Catch by 5x5 grid -->
<!-- # <!-- RMFO/RFB data, by ocean, by region, by RFMO/RFB, by species group, by species --> -->
<!-- # -->
<!-- # <!-- Can include a filter for annual or monthly data --> -->
<!-- # -->
<!-- # -->
<!-- # ### Size frequency -->
<!-- # <!-- By ocean, region, rfmo/rfb, species group, species, by gear, by Time_step scale (total, by decade) --> -->
<!-- # -->
<!-- # -->
<!-- # -->
<!-- # Stock assessment outputs -->
<!-- # ===================================== -->
<!-- # Select input {.sidebar} -->
<!-- # ------------------------------------------------- -->
<!-- # **Please select which stock to plot HERE ** -->
<!-- # -->
<!-- # ```{r} -->
<!-- # selectizeInput(inputId='Ocean', -->
<!-- #                label='Select ocean', -->
<!-- #                choices=as.character(unique(run_parameters$Ocean)), -->
<!-- #                selected='Indian', -->
<!-- #                multiple = FALSE) -->
<!-- # -->
<!-- # output$Region <- renderUI({ -->
<!-- #   selectizeInput("Region", -->
<!-- #                  label="Region(s)", -->
<!-- #                  choices =  unique(as.character(run_parameters$Region[run_parameters$Ocean==input$Ocean])), -->
<!-- #                  # selected=as.character(run_parameters$Run[1]), -->
<!-- #                  selected=unique(as.character(run_parameters$Region[run_parameters$Ocean==input$Ocean]))[1], -->
<!-- #                  multiple=TRUE)}) -->
<!-- # uiOutput("Region") -->
<!-- # -->
<!-- # output$Management_Authority <- renderUI({ -->
<!-- #   selectizeInput("Management Body/Authority", -->
<!-- #                  label="Management body/authority", -->
<!-- #                  choices =  unique(as.character(run_parameters$Management_Authority[run_parameters$Ocean==input$Ocean])), -->
<!-- #                  # selected=as.character(run_parameters$Run[1]), -->
<!-- #                  selected=unique(as.character(run_parameters$Management_Authority[run_parameters$Ocean==input$Ocean]))[1], -->
<!-- #                  multiple=FALSE)}) -->
<!-- # uiOutput("Management_Authority") -->
<!-- # -->
<!-- # output$Stock <- renderUI({ -->
<!-- #   selectizeInput("Stock", -->
<!-- #                  label="Choose the stock to plot", -->
<!-- #                  choices =  unique(as.character(run_parameters$Stock[run_parameters$Ocean==input$Ocean])), -->
<!-- #                  # selected=as.character(run_parameters$Run[1]), -->
<!-- #                  selected=unique(as.character(run_parameters$Stock[run_parameters$Ocean==input$Ocean]))[1], -->
<!-- #                  multiple=FALSE)# <------------------------------------------------------------------------------multiple may beinteresting for comparison -->
<!-- # }) -->
<!-- # uiOutput("Stock") -->
<!-- # -->
<!-- # output$Assessment_Year <- renderUI({ -->
<!-- #   selectizeInput("Assessment Year", -->
<!-- #                  label="Assessment year (if applicable)", -->
<!-- #                  choices =  unique(as.character(run_parameters$Assessment_Year[run_parameters$Ocean==input$Ocean])), -->
<!-- #                  # selected=as.character(run_parameters$Run[1]), -->
<!-- #                  selected=unique(as.character(run_parameters$Assessment_Year[run_parameters$Ocean==input$Ocean]))[1], -->
<!-- #                  multiple=FALSE)# <------------------------------------------------------------------------------multiple may be interesting for comparison -->
<!-- # }) -->
<!-- # uiOutput("Assessment_Year") -->
<!-- # -->
<!-- # # htmlOutput("selectUI") -->
<!-- # ``` -->
<!-- # -->
<!-- # -->
<!-- # Row {.tabset .tabset-fade} -->
<!-- # ------------------------------------- -->
<!-- # -->
<!-- # ### CPUE Fit -->
<!-- # <!-- Compare observations (black) against the predictions (colored) of selected SS3 model/run(s) for CPUE.  --> -->
<!-- # -->
<!-- # ```{r} -->
<!-- # renderPlotly({ -->
<!-- #   CPUE2plot <- CPUE_plot() -->
<!-- #   ############# CPUE FIT: OBSERVED V PREDICTED ########### -->
<!-- #   p <- ggplot(na.exclude(CPUE2plot), aes(x=Year, y=Obs)) -->
<!-- #   p <- p+geom_point(size=0.7,col='black')+geom_line(col='black')+geom_line(aes(y=Exp, colour=Model_run))+ -->
<!-- #     facet_wrap(~Fleet,ncol=2)#+scales='free_y'+ggtitle("CPUE fit: Observed v Predicted")#as.numeric(as.character(input$Run))) -->
<!-- #   ggplotly(p) -->
<!-- #   ######################################################## -->
<!-- # }) -->
<!-- # -->
<!-- # ``` -->
<!-- # -->
<!-- # ### CPUE residuals -->
<!-- # ```{r} -->
<!-- # renderPlotly({ -->
<!-- #   CPUE2plot <- CPUE_plot() -->
<!-- #   ################# CPUE STANDARDIZED RESIDUALS ################### -->
<!-- #   p <- ggplot(na.exclude(CPUE2plot), aes(x=Year, y=stDev, colour=Model_run)) -->
<!-- #   p <-  p+geom_point()+geom_line()+ -->
<!-- #     facet_wrap(~Fleet,ncol=2)+geom_abline(intercept = -2,slope=0, col="blue",linetype=2)+ -->
<!-- #     geom_abline(intercept = 2,slope=0, col="blue",linetype=2)+ -->
<!-- #     geom_abline(intercept = 0,slope=0, col="blue",linetype=2)#+ggtitle("Standardized CPUE residuals") -->
<!-- #   ggplotly(p) -->
<!-- #   ################################################################# -->
<!-- # }) -->
<!-- # ``` -->
<!-- # -->
<!-- # -->
<!-- # -->
<!-- # Row {.tabset .tabset-fade} -->
<!-- # ------------------------------------- -->
<!-- # -->
<!-- # ### Aggregated Length Frequency -->
<!-- # <!-- <!-- Size frequency by fleet, including mean aggregated length frequency (cm), mean length distribution (cm), and mean weight distribution (kg). --> --> -->
<!-- # -->
<!-- # ```{r} -->
<!-- # renderPlotly({ -->
<!-- #   LEN2plot <- LEN_plot() -->
<!-- #   ###################### AGGREGATE LENGTH FREQUENCY ######################## -->
<!-- #   forLen <- ddply(na.exclude(LEN2plot), .(Fleet,Bin,Model_run), function(x) data.frame(Obs=sum(x$Obs), Exp=sum(x$Exp))) -->
<!-- # -->
<!-- #   p <- ggplot(forLen, aes(x=Bin, y=Obs)) -->
<!-- #   p <- p+geom_bar(stat="identity")+facet_wrap(~Fleet, ncol=3, scales="free")+ -->
<!-- #     geom_line(aes(y=Exp,colour=Model_run))+ylab('Observations')+xlab('Length bin (cm)')#+ -->
<!-- #   # ggtitle("Aggregated length frequency") -->
<!-- #   ggplotly(p) -->
<!-- #   ########################################################################## -->
<!-- # }) -->
<!-- # ``` -->
<!-- # -->
<!-- # ### Mean Length Distribution -->
<!-- # ```{r} -->
<!-- # renderPlotly({ -->
<!-- #   LEN2plot<-LEN_plot() -->
<!-- #   ##################### MEAN LENGTH DISTRIBUTION ########################### -->
<!-- #   forLen2 <- ddply(na.exclude(LEN2plot), .(Fleet,Year,Model_run), function(x) data.frame(Obs=weighted.mean(x=x$Bin, w=x$Obs), -->
<!-- #                                                                                          Exp=weighted.mean(x=x$Bin, w=x$Exp) )) -->
<!-- #   p <- ggplot(forLen2, aes(x=Year, y=Obs)) -->
<!-- #   p <- p+geom_point()+geom_line(col="black")+geom_line(aes(y=Exp,colour=Model_run))+ -->
<!-- #     facet_wrap(~Fleet,scales = 'free', ncol=3)+ylab('Length (cm)') -->
<!-- #   ggplotly(p) -->
<!-- #   ########################################################################## -->
<!-- # }) -->
<!-- # -->
<!-- # ``` -->
<!-- # -->
<!-- # -->
<!-- # -->
<!-- # ### Mean Weight Distribution -->
<!-- # ```{r} -->
<!-- # renderPlotly({ -->
<!-- #   LEN2plot<-LEN_plot() -->
<!-- #   ##################### MEAN LENGTH DISTRIBUTION ########################### -->
<!-- #   forLenWeight <- ddply(na.exclude(LEN2plot), .(Fleet,Year,Model_run), function(x) data.frame(Obs=3.815e-006*(weighted.mean(x=x$Bin, w=x$Obs))^3.188,                                                     Exp= 3.815e-006*(weighted.mean(x=x$Bin, w=x$Exp))^3.188 )) -->
<!-- #   p <- ggplot(forLenWeight, aes(x=Year, y=Obs)) -->
<!-- #   p <- p+geom_point()+geom_line(col="black")+geom_line(aes(y=Exp,colour=Model_run))+ -->
<!-- #     facet_wrap(~Fleet, scales='free',ncol=3)+ylab('Weight (kg)') -->
<!-- #   ggplotly(p) -->
<!-- #   ########################################################################## -->
<!-- # }) -->
<!-- # ``` -->
<!-- # -->
<!-- # -->
<!-- # -->
<!-- # Row {.tabset .tabset-fade} -->
<!-- # ------------------------------------- -->
<!-- # -->
<!-- # ### Total Biomass by Area -->
<!-- # <!-- Biomass figures, including total biomass (1000 t), depletion (%), and spawning stock biomass (SSB; 1000 t): by area and summed over areas. --> -->
<!-- # -->
<!-- # ```{r} -->
<!-- # renderPlotly({ -->
<!-- #   Bioplot<-Bio_plot() -->
<!-- #   ########################## TOTAL BIOMASS BY AREA ######################## -->
<!-- #   end_current_period=max(Bioplot$Year[Bioplot$Era=='TIME' & is.na(Bioplot$bio)==FALSE]) -->
<!-- #   # req(is.null(which(colnames(Bioplot)=='Area'))) -->
<!-- #   if(length(intersect(colnames(Bioplot),'Area'))>0){ ## check that the model is multi-area -->
<!-- #     forBA <- ddply(na.exclude(Bioplot), .(Area,Year,Model_run), -->
<!-- #                    function(x) data.frame(bio=sum(x$bio[x$Era=="TIME"|x$Era=="FORE"],na.rm=T)/1000)) -->
<!-- #     forBA0<-forBA[which(forBA$bio>0),] -->
<!-- # -->
<!-- #     p <- ggplot(forBA0, aes(x=Year, y=bio,colour=Model_run)) -->
<!-- #     p <- p+geom_line(stat="identity")+facet_wrap(~Area, ncol=2)+ylab('Total Biomass (x1000 t)')+ -->
<!-- #       geom_vline(xintercept = end_current_period,col="blue",linetype=2) -->
<!-- #     ggplotly(p) -->
<!-- # -->
<!-- #   }else{  ## condition if single-area model, will plot total biomass -->
<!-- # -->
<!-- #     forBAtot <- ddply(na.exclude(Bioplot), .(Year,Model_run), -->
<!-- #                       function(x) data.frame(bio=sum(x$bio[x$Era=="TIME"|x$Era=="FORE"],na.rm=T)/1000)) -->
<!-- #     forBAtot0<-forBAtot[which(forBAtot$bio>0),] -->
<!-- # -->
<!-- #     p <- ggplot(forBAtot0, aes(x=Year, y=bio,colour=Model_run)) -->
<!-- #     p <- p+geom_line(stat="identity")+ylab('Total Biomass (x1000 t)')+ylim(range(forBAtot$bio))+ -->
<!-- #       geom_vline(xintercept = end_current_period,col="blue",linetype=2)+ggtitle('single-area model') -->
<!-- #     ggplotly(p) -->
<!-- #   } -->
<!-- #   ######################################################################### -->
<!-- # }) -->
<!-- # ``` -->
<!-- # -->
<!-- # -->
<!-- # ### Total Biomass -->
<!-- # ```{r} -->
<!-- # renderPlotly({ -->
<!-- #   Bioplot<-Bio_plot() -->
<!-- #   end_current_period=max(Bioplot$Year[Bioplot$Era=='TIME' & is.na(Bioplot$bio)==FALSE]) -->
<!-- #   ########################## TOTAL BIOMASS (SUMMED OVER AREA) ######################## -->
<!-- #   forBAtot <- ddply(na.exclude(Bioplot), .(Year,Model_run), -->
<!-- #                     function(x) data.frame(bio=sum(x$bio[x$Era=="TIME"|x$Era=="FORE"],na.rm=T)/1000)) -->
<!-- #   forBAtot0<-forBAtot[which(forBAtot$bio>0),] -->
<!-- # -->
<!-- #   p <- ggplot(forBAtot0, aes(x=Year, y=bio,colour=Model_run)) -->
<!-- #   p <- p+geom_line(stat="identity")+ylab('Total Biomass (x1000 t)')+ylim(range(forBAtot$bio))+ -->
<!-- #     geom_vline(xintercept = end_current_period,col="blue",linetype=2) -->
<!-- #   ggplotly(p) -->
<!-- #   ######################################################################### -->
<!-- # }) -->
<!-- # ``` -->
<!-- # -->
<!-- # -->
<!-- # ### Depletion by Area -->
<!-- # ```{r} -->
<!-- # renderPlotly({ -->
<!-- #   Bioplot<-Bio_plot() -->
<!-- #   end_current_period=max(Bioplot$Year[Bioplot$Era=='TIME' & is.na(Bioplot$bio)==FALSE]) -->
<!-- # -->
<!-- #   if(length(intersect(colnames(Bioplot),'Area'))>0){ -->
<!-- #     forBA <- ddply(na.exclude(Bioplot), .(Area,Year,Model_run), -->
<!-- #                    function(x) data.frame(bio=sum(x$bio[x$Era=="TIME"|x$Era=="FORE"],na.rm=T)/1000)) -->
<!-- #     forBA0<-forBA[which(forBA$bio>0),] -->
<!-- # -->
<!-- #     ######################## % DEPLETION BY AREA ############################ -->
<!-- #     p <- ggplot(forBA0, aes(x=Year, y=bio/bio[1]*100,colour=Model_run)) -->
<!-- #     p <- p+geom_line(stat="identity")+facet_wrap(~Area, ncol=2)+ylab('Depletion (%)')+ -->
<!-- #       geom_hline(yintercept=40,col='dark grey')+ -->
<!-- #       geom_vline(xintercept = end_current_period,col="blue",linetype=2) -->
<!-- #     ggplotly(p) -->
<!-- #     ######################################################################### -->
<!-- #   }else{ -->
<!-- #     forBAtot <- ddply(na.exclude(Bioplot), .(Year,Model_run), -->
<!-- #                       function(x) data.frame(bio=sum(x$bio[x$Era=="TIME"|x$Era=="FORE"],na.rm=T)/1000)) -->
<!-- #     forBAtot0<-forBAtot[which(forBAtot$bio>0),] -->
<!-- # -->
<!-- #     p <- ggplot(forBAtot0, aes(x=Year, y=bio/bio[1]*100,colour=Model_run)) -->
<!-- #     p <- p+geom_line(stat="identity")+ylab('Depletion (%)')+ylim(0,max(forBAtot0$bio/forBAtot0$bio[1]*100))+ -->
<!-- #       geom_hline(yintercept=40,col='dark grey')+ -->
<!-- #       geom_vline(xintercept = end_current_period,col="blue",linetype=2)+ggtitle('single-area model') -->
<!-- #     ggplotly(p) -->
<!-- #   } -->
<!-- # }) -->
<!-- # ``` -->
<!-- # -->
<!-- # ### Depletion -->
<!-- # ```{r} -->
<!-- # renderPlotly({ -->
<!-- #   Bioplot<-Bio_plot() -->
<!-- #   end_current_period=max(Bioplot$Year[Bioplot$Era=='TIME' & is.na(Bioplot$bio)==FALSE]) -->
<!-- # -->
<!-- #   ##################### % DEPLETION (SUMMED OVER AREAS) ################### -->
<!-- #   forBAtot <- ddply(na.exclude(Bioplot), .(Year,Model_run), -->
<!-- #                     function(x) data.frame(bio=sum(x$bio[x$Era=="TIME"|x$Era=="FORE"],na.rm=T)/1000)) -->
<!-- #   forBAtot0<-forBAtot[which(forBAtot$bio>0),] -->
<!-- # -->
<!-- #   p <- ggplot(forBAtot0, aes(x=Year, y=bio/bio[1]*100,colour=Model_run)) -->
<!-- #   p <- p+geom_line(stat="identity")+ylab('Depletion (%)')+ylim(0,max(forBAtot0$bio/forBAtot0$bio[1]*100))+ -->
<!-- #     geom_hline(yintercept=40,col='dark grey')+ -->
<!-- #     geom_vline(xintercept = end_current_period,col="blue",linetype=2) -->
<!-- #   ggplotly(p) -->
<!-- #   ######################################################################### -->
<!-- # }) -->
<!-- # ``` -->
<!-- # -->
<!-- # -->
<!-- # ### SSB by Area -->
<!-- # ```{r} -->
<!-- # renderPlotly({ -->
<!-- #   SSBplot<-SSB_plot() -->
<!-- #   if(length(intersect(colnames(SSBplot),'Area'))>0){ -->
<!-- #     #################### SPAWNING STOCK BIOMASS BY AREA ##################### -->
<!-- #     forSSB <- ddply(na.exclude(SSBplot), .(Area,Year,Model_run), -->
<!-- #                     function(x) data.frame(spbio=sum(x$spbio[x$Era=="TIME"]))) ### <--AEN: GLOBAL ATTRIBUTES FOR CHARACTERS!!! -->
<!-- #     zeros=which(forSSB$spbio>0) -->
<!-- #     forSSB<-forSSB[zeros,] -->
<!-- # -->
<!-- #     p <- ggplot(forSSB, aes(x=Year, y=spbio,colour=Model_run)) -->
<!-- #     p <- p+geom_line(stat="identity")+facet_wrap(~Area, ncol=2)+ylab('Spawning Biomass (x1000 t)') -->
<!-- #     ggplotly(p) -->
<!-- #     ########################################################################## -->
<!-- #   }else{ -->
<!-- #     forSSBtot <- ddply(na.exclude(SSBplot), .(Year,Model_run), -->
<!-- #                        function(x) data.frame(spbio=sum(x$spbio[x$Era=="TIME"]))) -->
<!-- #     forSSBtot0<-forSSBtot[which(forSSBtot$spbio>0),] -->
<!-- # -->
<!-- #     p <- ggplot(forSSBtot0, aes(x=Year, y=spbio,colour=Model_run)) -->
<!-- #     p <- p+geom_line(stat="identity")+ylab('Spawning Biomass (x1000 t)')+ggtitle('single-area model') -->
<!-- #     ggplotly(p) -->
<!-- #   } -->
<!-- # }) -->
<!-- # ``` -->
<!-- # -->
<!-- # ### SSB -->
<!-- # ```{r} -->
<!-- # renderPlotly({ -->
<!-- #   SSBplot<-SSB_plot() -->
<!-- #   ####################### SPAWNING STOCK BIOMASS ########################### -->
<!-- #   forSSBtot <- ddply(na.exclude(SSBplot), .(Year,Model_run), -->
<!-- #                      function(x) data.frame(spbio=sum(x$spbio[x$Era=="TIME"]))) -->
<!-- #   forSSBtot0<-forSSBtot[which(forSSBtot$spbio>0),] -->
<!-- # -->
<!-- #   p <- ggplot(forSSBtot0, aes(x=Year, y=spbio,colour=Model_run)) -->
<!-- #   p <- p+geom_line(stat="identity")+ylab('Spawning Biomass (x1000 t)') -->
<!-- #   ggplotly(p) -->
<!-- #   # ########################################################################## -->
<!-- # }) -->
<!-- # ``` -->
<!-- # -->
<!-- # -->
<!-- # Row {.tabset .tabset-fade} -->
<!-- # ------------------------------------- -->
<!-- # -->
<!-- # ### Fishing mortality -->
<!-- # <!-- Compare observations against the predictions of selected SS3 model(s) for fishing mortality.  --> -->
<!-- # -->
<!-- # <!-- ## F/F_msy --> -->
<!-- # ```{r} -->
<!-- # renderPlotly({ -->
<!-- #   FFMSYplot<-FFMSY_plot() -->
<!-- #   ####################### FFMSY (SUMMED OVER AREAS) ########################### -->
<!-- #   p <- ggplot(FFMSYplot, aes(x=Year, y=FFmsy,colour=Model_run)) -->
<!-- #   p <- p+geom_line(stat="identity")+ylab('F/Fmsy') -->
<!-- #   ggplotly(p) -->
<!-- #   ########################################################################## -->
<!-- # }) -->
<!-- # ``` -->
<!-- # -->
<!-- # -->
<!-- # -->
<!-- # Row {.tabset .tabset-fade} -->
<!-- # ------------------------------------- -->
<!-- # -->
<!-- # ### Recruitment Deviation -->
<!-- # <!-- Compare observations against the predictions of selected SS3 model(s) for recruitment deviation, recruitment (millions) by area, and summed over area  (millions).  --> -->
<!-- # -->
<!-- # <!-- Row {.tabset .tabset-fade} --> -->
<!-- # <!-- ------------------------------------- --> -->
<!-- # -->
<!-- # ```{r} -->
<!-- # renderPlotly({ -->
<!-- #   # RecDevplot<-RecDev_plot() -->
<!-- #   xx <- rnorm(1000,0,0.2) -->
<!-- #   x1 <- quantile(xx, 0.025) -->
<!-- #   x2 <- quantile(xx, 0.975) -->
<!-- # -->
<!-- #   # ####################### RECRUITMENT DEVIATION ########################### -->
<!-- #   # plot(RecDevplot$Year, RecDevplot$value, type="l", lwd=2, xlab="Year", ylab="Rec dev", ylim=c(min(x1,RecDevplot$value,na.rm=T),max(x2,RecDevplot$value,na.rm=TRUE)), xaxt ="n") -->
<!-- #   # -->
<!-- #   # # polygon(c(RecDevplot$Year, rev(RecDevplot$Year)), c(RecDevplot$uci, rev(RecDevplot$lci)), border=NA, col="light grey" ) -->
<!-- #   # -->
<!-- #   # lines(RecDevplot$Year, RecDevplot$value, lwd=2) -->
<!-- #   # axis(1, at=seq(min(RecDevplot$Year),max(RecDevplot$Year),5)) -->
<!-- #   # lines(range(RecDevplot$Year), rep(0,2), lty=3) -->
<!-- #   # lines(range(RecDevplot$Year), rep(x1,2), lty=4, col="blue") -->
<!-- #   # lines(range(RecDevplot$Year), rep(x2,2), lty=4, col="blue") -->
<!-- #   # ########################################################################## -->
<!-- #   # -->
<!-- #   # -->
<!-- # -->
<!-- #   RecDevplot<-RecDev_plot() -->
<!-- #   ####################### RECRUITMENT (SUMMED OVER AREAS) ########################### -->
<!-- #   forRecDev <- ddply(na.exclude(RecDevplot), .(Year,Model_run), -->
<!-- #                      function(x) data.frame(value=sum(x$value))) -->
<!-- #   # zeros=which(forRecDev$rec0>0) -->
<!-- #   # forRecDev<-forRecDev[zeros,] -->
<!-- # -->
<!-- #   p <- ggplot(forRecDev, aes(x=Year, y=value,colour=Model_run)) -->
<!-- #   p <- p+geom_line(stat="identity")+ylab('Recruitment deviation')+ -->
<!-- #     geom_hline(yintercept=x1,col='blue')+ -->
<!-- #     geom_hline(yintercept=x2,col='blue')+ -->
<!-- #     geom_hline(yintercept=0,col='blue') -->
<!-- #   ggplotly(p) -->
<!-- #   ########################################################################## -->
<!-- # -->
<!-- # -->
<!-- # }) -->
<!-- # ``` -->
<!-- # -->
<!-- # ### Recruitment by Area -->
<!-- # ```{r} -->
<!-- # renderPlotly({ -->
<!-- #   R0plot<-R0_plot() -->
<!-- #   if(length(intersect(colnames(R0plot),'Area'))>0){ -->
<!-- #     ####################### RECRUITMENT BY AREA ########################### -->
<!-- #     forR0 <- ddply(na.exclude(R0plot), .(Area,Year,Model_run), -->
<!-- #                    function(x) data.frame(rec0=sum(x$rec0[x$Era=="TIME"]))) ### <--AEN: GLOBAL ATTRIBUTES FOR CHARACTERS!!! -->
<!-- #     zeros=which(forR0$rec0>0) -->
<!-- #     forR0<-forR0[zeros,] -->
<!-- # -->
<!-- #     p <- ggplot(forR0, aes(x=Year, y=rec0,colour=Model_run)) -->
<!-- #     p <- p+geom_line(stat="identity")+facet_wrap(~Area, ncol=2)+ylab('Recruit 0 (millions)') -->
<!-- #     ggplotly(p) -->
<!-- #     ########################################################################## -->
<!-- #   }else{ -->
<!-- #     forR0 <- ddply(na.exclude(R0plot), .(Year,Model_run), -->
<!-- #                    function(x) data.frame(rec0=sum(x$rec0[x$Era=="TIME"]))) ### <--AEN: GLOBAL ATTRIBUTES FOR CHARACTERS!!! -->
<!-- #     zeros=which(forR0$rec0>0) -->
<!-- #     forR0<-forR0[zeros,] -->
<!-- # -->
<!-- #     p <- ggplot(forR0, aes(x=Year, y=rec0,colour=Model_run)) -->
<!-- #     p <- p+geom_line(stat="identity")+ylab('Recruit 0 (millions)')+ggtitle('single-area model') -->
<!-- #     ggplotly(p) -->
<!-- #   } -->
<!-- # }) -->
<!-- # ``` -->
<!-- # -->
<!-- # -->
<!-- # -->
<!-- # ### Total Recruitment -->
<!-- # ```{r} -->
<!-- # renderPlotly({ -->
<!-- #   R0plot<-R0_plot() -->
<!-- #   ####################### RECRUITMENT (SUMMED OVER AREAS) ########################### -->
<!-- #   forR0 <- ddply(na.exclude(R0plot), .(Year,Model_run), -->
<!-- #                  function(x) data.frame(rec0=sum(x$rec0[x$Era=="TIME"]))) ### <--AEN: GLOBAL ATTRIBUTES FOR CHARACTERS!!! -->
<!-- #   zeros=which(forR0$rec0>0) -->
<!-- #   forR0<-forR0[zeros,] -->
<!-- # -->
<!-- #   p <- ggplot(forR0, aes(x=Year, y=rec0,colour=Model_run)) -->
<!-- #   p <- p+geom_line(stat="identity")+ylab('Recruit 0 (millions)') -->
<!-- #   ggplotly(p) -->
<!-- #   ########################################################################## -->
<!-- # }) -->
<!-- # ``` -->
<!-- # -->
<!-- # -->
<!-- # Row {.tabset .tabset-fade} -->
<!-- # ------------------------------------- -->
<!-- # ### Size Selectivity -->
<!-- # Size and age selectivity. Size selectivity by fleet defined as "Lsel" (cm)  in the latest year of the assessment. -->
<!-- # -->
<!-- # ```{r} -->
<!-- # renderPlotly({ -->
<!-- #   Sselplot<-Ssel_plot() -->
<!-- #   ####################### SIZE SELECTIVITY BY FLEET ########################### -->
<!-- #   if(length(grep('Gender',colnames(Sselplot)))>0){ forSize <- ddply(na.exclude(Sselplot), .(Fleet,Size,Model_run), -->
<!-- #                                                                     function(x) data.frame(x[x$Gender==1 & x$Factor=="Lsel" & x$Year==x$endyr,])) -->
<!-- #   }else{forSize <- ddply(na.exclude(Sselplot), .(Fleet,Size,Model_run), -->
<!-- #                          function(x) data.frame(x[x$Factor=="Lsel" & x$Year==x$endyr,]))} -->
<!-- #   p <- ggplot(forSize, aes(x=Size, y=sel,colour=Model_run)) -->
<!-- #   p <- p+geom_line(stat="identity")+facet_wrap(~Fleet, ncol=5, scales="free")+xlab('Length (cm)')+ylab('Proportion')#+ -->
<!-- #   ggplotly(p) -->
<!-- #   ########################################################################## -->
<!-- # }) -->
<!-- # ``` -->
<!-- # -->
<!-- # ### Age Selectivity -->
<!-- # ```{r} -->
<!-- # renderPlotly({ -->
<!-- #   Aselplot<-Asel_plot() -->
<!-- #   req(!is.null(Aselplot)) -->
<!-- #   ####################### SIZE SELECTIVITY BY FLEET ########################### -->
<!-- #   if(length(grep('Gender',colnames(Aselplot)))>0){ forAge <- ddply(na.exclude(Aselplot), .(Fleet,Age,Model_run), -->
<!-- #                                                                    function(x) data.frame(x[x$Gender==1 & x$Factor=="Asel" & x$Year==x$endyr,])) -->
<!-- #   }else{forAge <- ddply(na.exclude(Aselplot), .(Fleet,Age,Model_run), -->
<!-- #                         function(x) data.frame(x[x$Factor=="Asel" & x$Year==x$endyr,]))} -->
<!-- #   p <- ggplot(forAge, aes(x=Age, y=sel,colour=Model_run)) -->
<!-- #   p <- p+geom_line(stat="identity")+facet_wrap(~Fleet, ncol=5, scales="free")+xlab('Length (cm)')+ylab('Proportion')#+ -->
<!-- #   ggplotly(p) -->
<!-- #   ########################################################################## -->
<!-- # }) -->
<!-- # ``` -->
<!-- # -->
<!-- # Row {.tabset .tabset-fade} -->
<!-- # ------------------------------------- -->
<!-- # ### Stock trajectory -->
<!-- # -->
<!-- # -->
<!-- # -->
<!-- # Ecological indicators -->
<!-- # ===================================== -->
<!-- # -->
<!-- # -->
<!-- # -->
<!-- # Environmental indicators -->
<!-- # ===================================== -->
<!-- # -->




