#R Script generated by OpenFairViewer (https://github.com/eblondel/OpenFairViewer) on 2021-01-18T12:11:16.460Z
#This script provides a standard way to get data and metadata handled in a OpenFairViewer application 

#Application details: 
# • OpenFairViewer Base URL: https://sdi-lab.d4science.org/sdi-lab/
# • OGC CSW Catalogue URL: https://geonetwork-sdi-lab.d4science.org/geonetwork/srv/eng/csw
#Dataset details: 
# • pid: fao_capture_flag_dbquery_advanced
# • title: FAO - Global capture production - Quantity (1950 - 2018) - Aggregated or raw capture data by year
# • abstract: This database contains capture production statistics by country or territory,species item,and FAO Major Fishing Area. This GIS product allows to browse sum of capture by countries and year,and allows to select one or more species,and one or more FAO major fishing area(s).
# • OpenFairViewer Query URL: https://sdi-lab.d4science.org/sdi-lab/?dataset=global_catch_1deg_1m_ps_bb_ird_level0&baseview=World%20Imagery&extent=-168.75,-85.166015625,168.75,85.166015625&center=0,0&zoom=3
#---------------------------------------------------------------------------------------------------------
#packages
if(!require(ows4R)){
	install.packages("ows4R")
	require(ows4R)
}

if(!require(sp)){
	install.packages("sp")
	require(sp)
}

#Dataset PID
pid <- "fao_capture_flag_dbquery_advanced"

layer <- "fao_capture_dbquery_layer_adv"

#Connect to OGC CSW Catalogue to get METADATA
CSW <- CSWClient$new(
	url = "https://geonetwork-sdi-lab.d4science.org/geonetwork/srv/eng/csw",
	serviceVersion = "2.0.2",
	logger = "INFO"
)
#Get metadata for dataset 'fao_capture_flag_dbquery_advanced'
md <- CSW$getRecordById(pid, outputSchema = "http://www.isotc211.org/2005/gmd")
fc <- CSW$getRecordById(paste0(pid,"_dsd"), outputSchema = "http://www.isotc211.org/2005/gfc")

#Connect to OGC WFS to get DATA
WFS <- WFSClient$new(
	url = "https://geoserver-sdi-lab.d4science.org/geoserver/sdilab_fisheriesatlas/ows",
	serviceVersion = "1.0.0",
	logger = "INFO"
)
#Get feature type for dataset 'fao_capture_flag_dbquery_advanced' (layer = 'fao_capture_dbquery_layer_adv' )
ft <- WFS$capabilities$findFeatureTypeByName(layer)
#Get data features for dataset 'fao_capture_flag_dbquery_advanced' (layer = 'fao_capture_dbquery_layer_adv' )
data.sf <- ft$getFeatures(viewparams = "year:2018;aggregation_method:none")
data.sp <- as(data.sf, "Spatial")
