#R Script generated by OpenFairViewer (https://github.com/eblondel/OpenFairViewer) on 2020-10-29T13:14:17.396Z
#This script provides a standard way to get data and metadata handled in a OpenFairViewer application 

#Application details: 
# • OpenFairViewer Base URL: http://sdi-lab.d4science.org/sdi-lab/
# • OGC CSW Catalogue URL: https://geonetwork-sdi-lab.d4science.org/geonetwork/srv/eng/csw
#Dataset details: 
# • pid: global_catch_1deg_1m_ps_bb_ird_level0
# • title: Monthly catch of tuna and tuna-like species (1950-01-01 - 2016-12-31) by purse seiners and pole-and-liners in the Indian, Atlantic and Eastern Pacific Oceans aggregated by statistical squares of 1° longitude and latitude (FIRMS level 0)
# • abstract: This dataset lists the monthly-spatially aggregated catch of tuna and tuna-like species (i.e. billfish,bonitos,and mackerel) by purse seiners and pole-and-liners from 1950-01-01 to 2016-12-31 in the Indian,Atlantic and Eastern Pacific Oceans. Species-specific catches expressed in weight or number are stratified by year,month,vessel flag reporting country,fishing gear,fishing mode (i.e. type of school association) and area (mainly statistical squares of 1° longitude and latitude). This dataset was computed using public domain catch datasets released by four of the five tuna Regional Fisheries Management Organizations:the Indian Ocean Tuna Commission (IOTC),the International Commission for the Conservation of Atlantic Tunas (ICCAT),the Inter-American Tropical Tuna Commission (IATTC)and the Commission for the Conservation of Southern Bluefin Tuna (CCSBT). Data from the Western Pacific Ocean were not included because WCPFC provides purse seine and pole-and-line catch at 5° square spatial resolution. IRD Level 0 stands for the processes applied to the primary datasets by the French National Research Institute for Sustainable Development (IRD).\n\nOriginal codes were mapped with standard FAO code lists for gears (ISSCFG),species (ASFIS) and flags (ISO3 countries codes) in collaboration with the tRFMOs Secretariats.\n- For the Southern Bluefin Tuna,only data from CCSBT were kept.\n\nMore details on the processes are provided in the supplemental information and in the lineage section.
# • OpenFairViewer Query URL: http://sdi-lab.d4science.org/sdi-lab/?dataset=global_catch_1deg_1m_ps_bb_ird_level0&baseview=World%20Imagery&extent=-168.75,-85.166015625,168.75,85.166015625&center=0,0&zoom=3
#---------------------------------------------------------------------------------------------------------
#packages
# library(pacman)
# p_load('ows4R','sp')
if(!require(ows4R)){
	install.packages("ows4R")
	require(ows4R)
}

if(!require(sp)){
	install.packages("sp")
	require(sp)
}

#Dataset PID
pid <- "global_catch_1deg_1m_ps_bb_ird_level0"

layer <- "global_catch_1deg_1m_ps_bb_ird_level0"

#Connect to OGC CSW Catalogue to get METADATA
CSW <- CSWClient$new(
	url = "https://geonetwork-sdi-lab.d4science.org/geonetwork/srv/eng/csw",
	serviceVersion = "2.0.2",
	logger = "INFO"
)
#Get metadata for dataset 'global_catch_1deg_1m_ps_bb_ird_level0'
md <- CSW$getRecordById(pid, outputSchema = "http://www.isotc211.org/2005/gmd")
fc <- CSW$getRecordById(paste0(pid,"_dsd"), outputSchema = "http://www.isotc211.org/2005/gfc")

#Connect to OGC WFS to get DATA
WFS <- WFSClient$new(
	url = "https://geoserver-sdi-lab.d4science.org/geoserver/sdilab_geoflow/ows",
	serviceVersion = "1.0.0",
	logger = "INFO"
)
#Get feature type for dataset 'global_catch_1deg_1m_ps_bb_ird_level0' (layer = 'global_catch_1deg_1m_ps_bb_ird_level0' )
ft <- WFS$capabilities$findFeatureTypeByName(layer)
#Get data features for dataset 'global_catch_1deg_1m_ps_bb_ird_level0' (layer = 'global_catch_1deg_1m_ps_bb_ird_level0' )
#@eblondel --> HERE you get the data from the OGC WFS service, given the query (viewparams). At the end of this query you have the "aggregation_method" set to the value you used in OFV. Set it to 'none' (instead of 'sum' here) to get all the raw data

data.sf <- ft$getFeatures(viewparams = "month:1+2+3+4+5+6+7+8+9+10+11+12;quarter:1+2+3+4;year:1950+1951+1952+1953+1954+1955+1956+1957+1958+1959+1960+1961+1962+1963+1964+1965+1966+1967+1968+1969+1970+1971+1972+1973+1974+1975+1976+1977+1978+1979+1980+1981+1982+1983+1984+1985+1986+1987+1988+1989+1990+1991+1992+1993+1994+1995+1996+1997+1998+1999+2000+2001+2002+2003+2004+2005+2006+2007+2008+2009+2010+2011+2012+2013+2014+2015+2016;unit:MT;aggregation_method:sum")

data.sf.2 <- data.sf[ ! st_is_empty( data.sf ) , ]

data.sp <- as(data.sf.2, "Spatial")

return()